catalog:
  "@tailwindcss/postcss": 4.0.0-alpha.24
  "@types/node": 22.5.5
  "@types/react": 18.3.8
  "@types/react-dom": 18.3.0
  "@typescript-eslint/eslint-plugin": 8.6.0
  "@typescript-eslint/parser": 8.6.0
  babel-plugin-react-compiler: 0.0.0-experimental-6067d4e-20240919
  eslint: 8.57.0
  eslint-config-next: 15.0.0-canary.160
  eslint-config-prettier: 9.1.0
  eslint-plugin-jsx-a11y: 6.10.0
  next: 15.0.0-canary.160
  postcss: 8.4.47
  prettier: 3.3.3
  prettier-plugin-tailwindcss: 0.6.6
  react: 19.0.0-rc-e740d4b1-20240919
  react-dom: 19.0.0-rc-e740d4b1-20240919
  server-only: 0.0.1
  tailwindcss: 4.0.0-alpha.24
  typescript: 5.6.2
packages:
  - "sites/*"
